import foodImg from 'public/classes/food.png';
import theme from 'theme';

export const ClassesData = [
    {
        id: 1,
        label: 'Lively',
        checkedColor: 'white',
        name: 'Lively',
        textColor: 'black',
    },
    {
        id: 2,
        label: 'A Totally new Take',
        checkedColor: 'white',
        name: 'A Totally new Take',
        textColor: 'black',
    },
    {
        id: 3,
        label: 'Intimate',
        checkedColor: 'white',
        name: 'Intimate',
        textColor: 'black',
    },
    {
        id: 4,
        label: 'Rigorous',
        checkedColor: 'white',
        name: 'Rigorous',
        textColor: 'black',
    },
    {
        id: 5,
        label: 'Structured',
        checkedColor: 'white',
        name: 'Structured',
        textColor: 'black',
    },
    {
        id: 6,
        label: 'informal',
        checkedColor: 'white',
        name: 'informal',
        textColor: 'black',
    },
    {
        id: 7,
        label: 'Dynamic',
        checkedColor: 'white',
        name: 'Dynamic',
        textColor: 'black',
    },
    {
        id: 8,
        label: 'Radical',
        name: 'Radical',
        checkedColor: 'white',
        textColor: 'black',
    },
    {
        id: 9,
        label: 'Surprising',
        name: 'Surprising',
        checkedColor: 'white',
        textColor: 'black',
    },
    {
        id: 10,
        label: 'Highly Interactive',
        name: 'Highly Interactive',
        checkedColor: 'white',
        textColor: 'black',
    },
    {
        id: 11,
        label: 'Multimedia',
        name: 'Multimedia',
        checkedColor: 'white',
        textColor: 'black',
    },
    {
        id: 12,
        label: 'Thought Provoking',
        name: 'Thought Provoking',
        checkedColor: 'white',
        textColor: 'black',
    },
];

export const EducatorData = [
    {
        id: 1,
        label: 'Passionate',
        checkedColor: 'white',
        name: 'Passionate',
        textColor: 'black',
    },
    {
        id: 2,
        label: 'Rigorous',
        checkedColor: 'white',
        name: 'Rigorous',
        textColor: 'black',
    },
    {
        id: 3,
        label: 'Funny',
        checkedColor: 'white',
        name: 'Funny',
        textColor: 'black',
    },
    {
        id: 4,
        label: 'Engaging',
        checkedColor: 'white',
        name: 'Engaging',
        textColor: 'black',
    },
    {
        id: 5,
        label: 'Accessible',
        checkedColor: 'white',
        name: 'Accessible',
        textColor: 'black',
    },
    {
        id: 6,
        label: 'Innovative',
        checkedColor: 'white',
        name: 'Innovative',
        textColor: 'black',
    },
    {
        id: 7,
        label: 'Creative',
        checkedColor: 'white',
        name: 'Creative',
        textColor: 'black',
    },
    {
        id: 8,
        label: 'Beloved',
        checkedColor: 'white',
        name: 'Beloved',
        textColor: 'black',
    },
];
export const orderHistoryData = [
    {
        id: 1,
        image: foodImg,
        status: 'Upcoming',
        color: theme.yellow.primary,
        time: '  August 5th - September 6th • 7:30 - 10:30PM EST',
        sessionCount: 3,
        title: '  Bob Dylan: Highway 61 Revisited, Blues, Poetry and Electricity',
        subTotal: '35.00',
        total: '0.00',
        ms: '35.00',
    },
    {
        id: 2,
        image: foodImg,
        status: 'Inprogress',
        color: theme.literature.primary,
        time: '  August 5th - September 6th • 7:30 - 10:30PM EST',
        sessionCount: 3,
        title: '  Bob Dylan: Highway 61 Revisited, Blues, Poetry and Electricity',
        subTotal: '35.00',
        total: '0.00',
        ms: '35.00',
    },
    {
        id: 3,
        image: foodImg,
        status: 'Finished',
        color: theme.navy.primary,
        time: '  August 5th - September 6th • 7:30 - 10:30PM EST',
        sessionCount: 3,
        title: '  Bob Dylan: Highway 61 Revisited, Blues, Poetry and Electricity',
        subTotal: '35.00',
        total: '0.00',
        ms: '35.00',
    },
];
